name: CI for Playwright C# project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Instalar .NET Core SDK
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x' # Usar la versión adecuada de .NET

      # Restaurar dependencias de NuGet
      - name: Restore NuGet packages
        run: dotnet restore

      # Compilar el proyecto
      - name: Build the project
        run: dotnet build --configuration Release --no-restore

      # Instalar Playwright CLI
      - name: Install Playwright CLI
        run: dotnet tool install --global Microsoft.Playwright.CLI
        env:
          DOTNET_ROOT: /home/runner/.dotnet

      # Instalar navegadores de Playwright usando dotnet
      - name: Install Playwright browsers
        run: dotnet playwright install
        env:
          DOTNET_ROOT: /home/runner/.dotnet

      # Ejecutar las pruebas
      - name: Run Playwright tests
        run: dotnet test --configuration Release --no-build
